### PR TITLE
Create use-wallet

### PR DESCRIPTION
**Pull request by ModernPortable**
use-wallet call

### CODE REVIEW

**Review by ModernPortable — COMMENTED** [review]
approved

**Review by Fergiu28 — APPROVED** [review]

**Review by Fergiu28 — APPROVED** [review]

**Review by Debu976116 — APPROVED** [review]

**Review by Debu976116 — APPROVED** [review]
Approve

**Comment by Eren0180** [comment]
> use-wallet call

ETH: 0xc57127d1e39CD421eBDa3444B8515fAf19F9C880, ETH: 0x137b7d86adaBeB3A69f5DD61fD9953579c8F58A7, SOL: 65gfwnceGDqvh2GjLW9Wnv9AtaNuj3QrugfbVX1ozvC1, SOL: Fy5FeKLJnsB4eBZFqd1LfEe1GojoxuFW6TL5XPAPkHHg, DOGE: xpub6CgfccHw62eYR7WEr3RMurtb6qayQZV9r6X6ScEgAcAVu641A5u4aajwjkUAxwZsQpg6NWYtFm6vhvA76WhZqQ7XC4Roq99uhYLBNu67SGp, BTC: xpub6CaWySqDvDVZ4yiDaAE7NWN9Y4whrvYayHPSnxWBKsBkUubtKSNa5hBdjH2dAx4mbXJhFogqNUkkCsbRPPWa4XbkuLTDhdZNEHjVbBEbADD, LTC: xpub6CE5Be2JX5ZSCsLNrBis7tZJXomzUao34rTjAEH6vXxrARm1xbLr3RCbhruAr43nmjqpo5LM1NaaN1gLJE6Y1cL7U6gSswYGdvRRvK5pGoQ

**Comment by Eren0180** [comment]
5

**Pull request closed without merging**
