### PR TITLE
chore: remove repetitive words

### PR DESCRIPTION
**Pull request by hugehope**

### CODE REVIEW

**Review by bradleyascott — APPROVED** [review]

**Review by bradleyascott — CHANGES_REQUESTED** [review]
trying to transion from smartchain to bnb beackon chain and connect to MetaMask portfolio

**Comment by octavio12345300** [comment]
listo

**Review by bradleyascott — APPROVED** [review]

**Comment by octavio12345300** [comment]
Listo

**Review by octavio12345300 — APPROVED** [review]

**Comment by bradleyascott** [comment]
Aprove , sorry still learning my addresses exploring the deep dive of things I guess to try to learn as much as I can in the crypto world and had hard time learning to merge sorry  😔 still working on it daily and first year in this still rookie beginner

**Comment by bradleyascott** [comment]
Thanks guys sorry I'm a rookie just a year in and just learning as much as
I can about crypto and my addresses,  sorry again for late reply

**Review by octavio12345300 — APPROVED** [review]

**Comment by bradleyascott** [comment]
Approve

**Comment by bradleyascott** [comment]
Approved.

**Review by robot-ux — APPROVED** [review]

**Pull request merged**
